# -*- coding: utf-8 -*-
"""python_basics_hema_susmitha.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6lGikHJwkNGbbZml4oiXq4b2COAvaKo

# Task 1: Variables and Data Types
"""

name = "hema susmitha"
age = 23
height = 5.4
is_student = False

print(name, age, height, is_student)

"""# Task 2: String Formatting

"""

print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")

"""# Task 3: Arithmetic Operations"""

age_in_months = age * 12
age_in_days = age * 365
remainder = age % 7
age_power = age ** 2

print("Age in months:", age_in_months)
print("Age in days:", age_in_days)
print("Remainder when age divided by 7:", remainder)
print("Age squared:", age_power)
